# Config for sdog
# policy_path: "logs/sdog/exported/policies/retrain_2450.pt"
policy_path: "logs/sdog/exported/policies/high_base_slow_pace.pt"
xml_path: "resources/robots/sdog/xml/sdog_copy.xml"

# Total simulation time
simulation_duration: 600.0
# Simulation time step
simulation_dt: 0.005
# Controller update frequency (meets the requirement of simulation_dt * controll_decimation=0.02; 50Hz)
control_decimation: 4

log_on: True
log_interval: 5

kps: 0.5
kds: 0.005

default_angles: [ 0.1000, 0.6000, -1.5000, # BL_hip_joint, BL_thigh_joint, BL_calf_joint
                  -0.1000, 0.6000, -1.5000, # BR_hip_joint, BR_thigh_joint, BR_calf_joint
                  0.1000, 0.6000, -1.5000, # FL_hip_joint, FL_thigh_joint, FL_calf_joint
                  -0.1000, 0.6000, -1.5000]  # FR_hip_joint, FR_thigh_joint, FR_calf_joint

ang_vel_scale: 0.5
dof_pos_scale: 1.0
dof_vel_scale: 0.1
action_scale: 0.25
cmd_scale: [10.0, 10.0, 0.5]
hip_reduction: 1.0

init_base_height: 0.11

num_actions: 12
num_obs: 45

cmd_init: [0.1 , 0.0, 0.0]
