# Config for sdog
policy_path: "logs/sdog/exported/policies/retrain_2450.pt"
# policy_path: "logs/sdog/exported/policies/policy_1.pt"
xml_path: "resources/robots/sdog/urdf/sdog.xml"

# Total simulation time
simulation_duration: 600.0
# Simulation time step
simulation_dt: 0.005
# Controller update frequency (meets the requirement of simulation_dt * controll_decimation=0.02; 50Hz)
control_decimation: 4

log_on: True
log_interval: 10


kps: 0.3
kds: 0.001
# kps: 0.5
# kds: 0.005

default_angles: [ 0.1000, 0.6000, -1.5000, # FL_hip_joint, FL_thigh_joint, FL_calf_joint
                  -0.1000, 0.6000, -1.5000, # FR_hip_joint, FR_thigh_joint, FR_calf_joint
                  0.1000, 0.6000, -1.5000, # RL_hip_joint, RL_thigh_joint, RL_calf_joint
                  -0.1000, 0.6000, -1.5000]  # RR_hip_joint, RR_thigh_joint, RR_calf_joint

ang_vel_scale: 0.5
dof_pos_scale: 1.0
dof_vel_scale: 0.1
action_scale: 0.25
cmd_scale: [10.0, 10.0, 0.5]
num_actions: 12
num_obs: 45
num_obs_frame: 6
hip_reduction: 1.0
cmd_init: [0.0, 0.0, 0.0]
